### ISSUE TITLE
ValueError: I/O operation on closed pipe

### ISSUE THREAD

**Issue by sonusporohealth** [mannaandpoem/OpenManus#521]
Not working. Requires more work!

`I will now save this blog post to a local file.
2025-03-12 13:38:25.506 | INFO     | app.agent.toolcall:think:54 - 🛠️ Manus selected 1 tools to use
2025-03-12 13:38:25.507 | INFO     | app.agent.toolcall:think:58 - 🧰 Tools being prepared: ['file_saver']
2025-03-12 13:38:25.507 | INFO     | app.agent.toolcall:execute_tool:140 - 🔧 Activating tool: 'file_saver'...
2025-03-12 13:38:25.510 | INFO     | app.agent.toolcall:act:113 - 🎯 Tool 'file_saver' completed its mission! Result: Observed output of cmd `file_saver` executed:
Content successfully saved to Balochistan_Blog_Post.txt
2025-03-12 13:38:25.511 | INFO     | app.agent.base:run:137 - Executing step 14/20
2025-03-12 13:38:27.986 | INFO     | app.agent.toolcall:think:53 - ✨ Manus's thoughts: The blog post on the recent developments in Balochistan has been successfully created and saved as "Balochistan_Blog_Post.txt". If you need any further assistance or modifications to the content, please let me know!
2025-03-12 13:38:28.005 | INFO     | app.agent.toolcall:think:54 - 🛠️ Manus selected 0 tools to use
2025-03-12 13:38:28.017 | INFO     | app.agent.base:run:137 - Executing step 15/20
2025-03-12 13:38:30.831 | INFO     | app.agent.toolcall:think:53 - ✨ Manus's thoughts: It seems there is a repeated message, and I want to ensure I address your request effectively. The blog post on the recent developments in Balochistan has been successfully created and saved as "Balochistan_Blog_Post.txt". If you have any further requests or need additional information, please let me know how I can assist you further!
2025-03-12 13:38:30.832 | INFO     | app.agent.toolcall:think:54 - 🛠️ Manus selected 0 tools to use
2025-03-12 13:38:30.832 | INFO     | app.agent.base:run:137 - Executing step 16/20
2025-03-12 13:38:32.484 | INFO     | app.agent.toolcall:think:53 - ✨ Manus's thoughts: None
2025-03-12 13:38:32.484 | INFO     | app.agent.toolcall:think:54 - 🛠️ Manus selected 1 tools to use
2025-03-12 13:38:32.485 | INFO     | app.agent.toolcall:think:58 - 🧰 Tools being prepared: ['terminate']
2025-03-12 13:38:32.485 | INFO     | app.agent.toolcall:execute_tool:140 - 🔧 Activating tool: 'terminate'...
2025-03-12 13:38:32.487 | INFO     | app.agent.toolcall:_handle_special_tool:172 - 🏁 Special tool 'terminate' has completed the task!
2025-03-12 13:38:32.487 | INFO     | app.agent.toolcall:act:113 - 🎯 Tool 'terminate' completed its mission! Result: Observed output of cmd `terminate` executed:
The interaction has been completed with status: success
2025-03-12 13:38:32.487 | INFO     | __main__:main:17 - Request processing completed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000019991EB2C00>
Traceback (most recent call last):
  File "C:\Python312\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Python312\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000019991EB1440>
Traceback (most recent call last):
  File "C:\Python312\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                        ^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe`

**Comment by EurekaTesla** [comment]
+1

**Comment by william11ya** [comment]
+1

**Comment by Abel-csd** [comment]
I've fixed this issue by installing the playwright.

**Comment by github0hello** [comment]
+1

**Comment by tapistefan** [comment]
Already asked here and still unresolved: https://github.com/mannaandpoem/OpenManus/issues/53
For me installing playwright doesn't fix the problem.
